config/routes.rb
Rails.application.routes.draw do
 
  
  
  root to: "sessions#home"

  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks", sessions: 'users/sessions', registrations: 'users/registrations' } 




  resources :groups, param: :invite_token do 
    resources :group_memberships, only: [:new, :create]
    resource :invite_link, only: :show
    resources :tasks 
  end





  
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :user
    belongs_to :group
    has_many :user_tasks
    
    accepts_nested_attributes_for :user


    validates :name, presence: true

    scope :most_recent, -> { order(created_at: :desc) }

    
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task
  before_action :set_group
  

    def index
        @tasks = @group.tasks
        @user_tasks = @group.tasks.where(user_id: current_user.id)
    end
    
    def show 
        @users = User.find_by_id(params[:user_id])
      end

      def new 
        @task = @group.tasks.create
      end
      
      def create
        @task = @group.tasks.create(task_params)
         if @task.save  
          flash[:success] = "Task was successfully created."
          redirect_to group_task_path(@group, @task)
        else
          flash[:danger] = "Task could not be created."
          render 'new'
        end
      end
      
      def edit
      end

      def update 
        @task = Task.find_by(params[:id])
        if @task.update(task_params)
          flash[:success] = "Task was successfully updated."
          redirect_to group_task_path(@group, @task)
        else 
          flash[:danger] = "Task could not be updated."
          render :edit 
        end
      end
    
      def destroy
        @task.destroy
        flash[:success] = "Task was successfully deleted."
        redirect_to group_tasks_path(@group, @task)
      end

      
  

      private

      def set_group 
        @group = Group.find_by_invite_token(params[:group_invite_token])
      end

      def set_task 
        @task = Task.find_by_id(params[:id])
      end
      
      def task_params
        params.require(:task).permit(:name, :completed, :user_id, users_attributes: [:id, :email, :_destroy])
      end
    end
    

app/views/tasks/edit.html.erb
<h1> Edit Task - <%= @task.name %> </h1>

<%= form_for [@group,@task], url: group_task_path do |f| %>
  <%= f.text_field :name %>
  
  <%= f.collection_select :user_id, @group.users, :id, :email, :prompt => 'Assign to a User', :required => true %><br>

  


  <%= f.submit "Update" %>
<% end %>

app/views/tasks/index.html.erb
<%= link_to 'Assign Tasks', new_group_task_path(@group) %><br><br>

<br>

<h5> Your Tasks | <%= current_user.email %> </h5>
<% @user_tasks.each do |task| %>
    <%= link_to task.name, group_task_path(@group,task) %>
    <%= link_to 'Done', group_task_path(@group,task), method: :delete %><br>
    
<% end %><br>
    <br><br>
<h5> <%= @group.name %> | Tasks </h5>

<% @group.tasks.most_recent.each do |t| %>
    <%= link_to t.name, group_task_path(@group,t) %>
    <%= t.user.email %><br>
    <% end %>

<br><br>

<%= link_to 'Back', groups_path, class: "btn btn-primary" %><br>

app/views/tasks/new.html.erb
<h1> New Task </h1>

<%= form_for [@group,@task], url: group_tasks_path do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>
    <%= f.collection_select :user_id, @group.users, :id, :email, :prompt => 'Assign to a User', :required => true %>
    <%= f.submit "Create" %>
<% end %>

app/views/tasks/show.html.erb
<div class="container">


<h5>Task | <%= @task.name %></h5>
<%= @task.user.email %>
<br>
<%= link_to 'Delete', group_task_path(@group,@task), method: :delete %><br>
    <%= link_to 'Edit', edit_group_task_path(@group,@task) %><br>
<%= link_to 'Back', group_tasks_path %><br>
</div>