config/routes.rb
Rails.application.routes.draw do
 
  
  
  root to: "sessions#home"

  devise_for :users, :controllers => {omniauth_callbacks: "users/omniauth_callbacks", sessions: 'users/sessions', registrations: 'users/registrations' } 




  resources :groups, param: :invite_token do 
    resources :group_memberships, only: [:new, :create]
    resource :invite_link, only: :show
    resources :tasks 
  end





  
end

app/models/group.rb
class Group < ApplicationRecord
    has_secure_token :invite_token
    
    has_many :group_memberships, dependent: :destroy
    has_many :users, through: :group_memberships
    
    has_many :tasks
    
   
    validates :name, presence: true
    
    
    def member?(user)
        users.include?(user)
    end

    def to_param 
        invite_token
    end


end

app/controllers/groups/invitations_controller.rb
class Groups::InvitationsController < DeviseController
    prepend_before_action :authenticate_inviter!, only: [:new, :create]
    prepend_before_action :has_invitations_left?, only: [:create]
    prepend_before_action :require_no_authentication, only: [:edit, :update, :destroy]
    prepend_before_action :resource_from_invitation_token, only: [:edit, :destroy]
  
    if respond_to? :helper_method
      helper_method :after_sign_in_path_for
    end
  
    # GET /resource/invitation/new
    def new
      @group = Group.find_by_id(params[:id])
      self.resource = resource_class.new
      render :new
    end
  
    # POST /resource/invitation
    def create
      @group = Group.find_by_id(params[:group_id])
      self.resource = invite_resource
      resource_invited = resource.errors.empty?
  
      yield resource if block_given?
  
      if resource_invited
        if is_flashing_format? && self.resource.invitation_sent_at
          set_flash_message :notice, :send_instructions, email: self.resource.email
        end
        if self.method(:after_invite_path_for).arity == 1
          respond_with resource, location: after_invite_path_for(current_inviter)
        else
          respond_with resource, location: after_invite_path_for(current_inviter, resource)
        end
      else
        respond_with_navigational(resource) { render :new }
      end
    end
  
    # GET /resource/invitation/accept?invitation_token=abcdef
    def edit
      set_minimum_password_length
      resource.invitation_token = params[:invitation_token]
      render :edit
    end
  
    # PUT /resource/invitation
    def update
      raw_invitation_token = update_resource_params[:invitation_token]
      self.resource = accept_resource
      invitation_accepted = resource.errors.empty?
  
      yield resource if block_given?
  
      if invitation_accepted
        if resource.class.allow_insecure_sign_in_after_accept
          flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
          set_flash_message :notice, flash_message if is_flashing_format?
          resource.after_database_authentication
          sign_in(resource_name, resource)
          respond_with resource, location: after_accept_path_for(resource)
        else
          set_flash_message :notice, :updated_not_active if is_flashing_format?
          respond_with resource, location: new_session_path(resource_name)
        end
      else
        resource.invitation_token = raw_invitation_token
        respond_with_navigational(resource) { render :edit }
      end
    end
  
    # GET /resource/invitation/remove?invitation_token=abcdef
    def destroy
      resource.destroy
      set_flash_message :notice, :invitation_removed if is_flashing_format?
      redirect_to after_sign_out_path_for(resource_name)
    end
  
    protected
  
      def invite_resource(&block)
        resource_class.invite!(invite_params, current_inviter, &block)
      end
  
      def accept_resource
        resource_class.accept_invitation!(update_resource_params)
      end
  
      def current_inviter
        authenticate_inviter!
      end
  
      def has_invitations_left?
        unless current_inviter.nil? || current_inviter.has_invitations_left?
          self.resource = resource_class.new
          set_flash_message :alert, :no_invitations_remaining if is_flashing_format?
          respond_with_navigational(resource) { render :new }
        end
      end
  
      def resource_from_invitation_token
        unless params[:invitation_token] && self.resource = resource_class.find_by_invitation_token(params[:invitation_token], true)
          set_flash_message(:alert, :invitation_token_invalid) if is_flashing_format?
          redirect_to after_sign_out_path_for(resource_name)
        end
      end
  
      def invite_params
        devise_parameter_sanitizer.sanitize(:invite)
      end
  
      def update_resource_params
        devise_parameter_sanitizer.sanitize(:accept_invitation)
      end
  
      def translation_scope
        'devise.invitations'
      end
  end
  

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    before_action :set_group
    def index
        @groups = current_user.groups
      end
    
      def show

      end

    def new 
        @group = current_user.groups.build
    end

    def create 
        @group = current_user.groups.build(group_params)
        @group.group_memberships.build(user_id: current_user.id)
        if @group.save
            redirect_to @group
            flash[:success] = "Group was successfully created."
        else
            flash[:danger] = "Group could not be created."
            render :new
        end
    end

    def edit 

    end

    def update
        if @group.update(group_params)
            redirect_to @group
            flash[:success] = "Group was successfully updated."
        else
            flash[:danger] = "Group could not be updated."
            render :edit
        end
    end

    def destroy 
        @group.destroy
        flash[:success] = "Group was successfully deleted."
        redirect_to groups_path

    end


    private 

    def set_group 
        @group = Group.find_by_invite_token(params[:invite_token])
    end

    def group_params 
        params.require(:group).permit(:name, :user_id, users_attributes: [:id, :email, :_destroy])
    end
end

app/views/groups/edit.html.erb
<h5> Edit Group | <%= @group.name %></h5><br>

<%= form_for @group do |f| %>
    <%= f.label :name %><br />
    <%= f.text_field :name, :required => true %>
    <%= f.submit %>
    <% end %>

app/views/groups/index.html.erb
<div class="container">
    <h5> Your Groups </h5>

  <ul>  <% current_user.groups.each do |g| %>
       <li> <%= link_to g.name, g %>
        <% end %></li><br><br>

        <%= link_to 'Create Group', new_group_path, class: "btn btn-success" %>  |
        <%= link_to 'Back', root_path, class: "btn btn-primary" %>

    </div>

app/views/groups/new.html.erb
<h5> New Group </h5>

<%= form_for @group do |f| %>
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true%>
    <%= f.submit %>
    <% end %>

app/views/groups/show.html.erb
<h5> Your Group | <%= @group.name %></h5>
<%= link_to "Edit", edit_group_path(@group) %> |
<%= link_to "Delete", @group, method: :delete, data: { confirm: "Are you sure?" } %><br>

            <div class="card-body">
              <div class="invite-box mb-4" data-controller="invite">
                <h5>Invite Link:</h5>
                <input class="group-url" id="cb-link-field" type="text" value="<%= new_group_group_membership_url(@group) %>" data-target="invite.url" data-group-token="<%= @group.invite_token %>"/>

                </div>
              </div>

              <h5> Members</h5>

             <ul> <% @group.group_memberships.each do |g| %>
              <li>  <%= g.user.email %>
                <% end %></li>
                </ul>

<%= link_to 'Group Tasks', group_tasks_path(@group), class: "btn btn-primary" %> |
<%= link_to 'Back', groups_path, class: "btn btn-primary" %>

        